name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  build-and-check:
    name: Build and checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run typecheck

      - name: Build (development env)
        run: npm run build

      - name: Build (test env)
        run: npm run build:test

      - name: Build (production env)
        run: npm run build:prod

      - name: Archive production build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
          if-no-files-found: ignore
