name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build

      - name: Make package script executable
        run: chmod +x scripts/package.sh

      - name: Package extension ZIP
        id: pkg
        run: |
          ./scripts/package.sh production
          echo "zip=$(ls -1 release/*.zip | head -n1)" >> "$GITHUB_OUTPUT"

      - name: Read version from manifest
        id: ver
        run: echo "version=$(jq -r .version manifest.json)" >> "$GITHUB_OUTPUT"

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: ${{ steps.pkg.outputs.zip }}
          if-no-files-found: error
          compression-level: 0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.ver.outputs.version }}-${{ github.sha }}
          name: v${{ steps.ver.outputs.version }} (PR #${{ github.event.pull_request.number }})
          generate_release_notes: true
          files: ${{ steps.pkg.outputs.zip }}

      - name: Upload to Chrome Web Store (optional)
        if: ${{ secrets.CHROME_CLIENT_ID != '' && secrets.CHROME_CLIENT_SECRET != '' && secrets.CHROME_REFRESH_TOKEN != '' && secrets.CHROME_EXTENSION_ID != '' }}
        uses: Klemensas/chrome-extension-deploy@v2
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          file-name: ${{ steps.pkg.outputs.zip }}
          app-id: ${{ secrets.CHROME_EXTENSION_ID }}
          publish: true
