jobs:
  bump:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR branch (read-only)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Decide bump level & compute next version
        id: prep
        run: |
          set -euo pipefail
          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH" | paste -sd, - || true)
          bump=patch
          case "$labels" in
            *release:major*) bump=major ;;
            *release:minor*) bump=minor ;;
          esac

          current=$(jq -r .version manifest.json)
          IFS='.' read -r MA MI PA <<<"$current"
          case "$bump" in
            major) MA=$((MA+1)); MI=0; PA=0 ;;
            minor) MI=$((MI+1)); PA=0 ;;
            patch) PA=$((PA+1)) ;;
          esac
          next="${MA}.${MI}.${PA}"

          echo "current=$current"; echo "next=$next"; echo "bump=$bump"
          echo "next=$next" >> "$GITHUB_OUTPUT"

      - name: Apply version bump to files
        run: |
          jq --arg v "${{ steps.prep.outputs.next }}" '.version=$v' manifest.json > manifest.tmp && mv manifest.tmp manifest.json
          if jq -e '.version' package.json >/dev/null 2>&1; then
            jq --arg v "${{ steps.prep.outputs.next }}" '.version=$v' package.json > package.tmp && mv package.tmp package.json
          fi

      - name: Open version-bump PR into the PR branch
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          commit-message: chore: bump version to ${{ steps.prep.outputs.next }}
          title: chore: bump version to ${{ steps.prep.outputs.next }} for PR #${{ github.event.pull_request.number }}
          body: Automated version bump for #${{ github.event.pull_request.number }}.
          branch: bot/bump-${{ steps.prep.outputs.next }}-for-${{ github.head_ref }}
          base: ${{ github.head_ref }}   # open PR into the contributor's PR branch
          delete-branch: true
          draft: false
          labels: automated

      - name: Try to enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --squash --delete-branch || true
