name: Version Bump on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  bump-version:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Get PR commit messages
        id: commits
        run: |
          MESSAGES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.commits_url }}" | jq -r '.[].commit.message' | tr '\n' ' ')
          echo "messages=$MESSAGES" >> "$GITHUB_OUTPUT"

      - name: Bump version
        id: bump
        run: node scripts/version-bump.js
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          COMMIT_MESSAGES: ${{ steps.commits.outputs.messages }}

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json package.json
          if git diff --staged --quiet; then
            echo "No version changes to commit."
          else
            git commit -m "build: Bump version to ${{ steps.bump.outputs.new_version }}" -m "[skip ci]"
            git push
          fi
